### ISSUE TITLE
Generation of particle roughness with larger D9_15

### ISSUE THREAD

**Issue by Debnathopu** [budizhao/SHPSG#2]
# particle roughness: larger D9_15 --> higher roughness
I was trying to create a rough sphere with the SHPSG but I can't do it. seems the effect of D9_15 is not reflected. 

Ei,Fi = 1,1
D2_8 = [0]

D9_15 = [0,  0.2, 0.5]

I want to generate such roughness for some numerical simulation.
![fig5](https://github.com/budizhao/SHPSG/assets/97938527/f1f8a4a4-1eff-4338-a771-69d8ab779f0c)

**Comment by budizhao** [comment]
Hi 

It’s not recommended to use D9_15 larger than 0.1. Please try with D9_15 = [0.01, 0.02, 0.05]. Also, you may need more surface elements by increasing level from 2 to 3 for example.

Many regards,

Budi

**Comment by Debnathopu** [comment]
Thank you very much for your prompt response. 
I tried for D9_15 = [0.01, 0.02, 0.05];  D2_8 = [0]; and level  up to 5
But I couldn't find the difference. Here is the output 
![D9_15](https://github.com/budizhao/SHPSG/assets/97938527/ae398c93-48f8-48dd-9fe0-37385b19f6a4)
for 0.01 to 0.05 (left to right)
